In [1]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)

In [2]:
a = np.array([[1,2,3,4],[1,1,2,3],[0,1,1,0]])
print(a)

[[1 2 3 4]
 [1 1 2 3]
 [0 1 1 0]]


In [3]:
u, s, vh = np.linalg.svd(a, full_matrices=True)
s

array([6.7509, 1.1734, 0.2186])

In [4]:
sd = np.diag(s)
sd

array([[6.7509, 0.    , 0.    ],
       [0.    , 1.1734, 0.    ],
       [0.    , 0.    , 0.2186]])

In [5]:
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
b[:,:-1] = sd

In [7]:
sigma = b
sigma

array([[6.7509, 0.    , 0.    , 0.    ],
       [0.    , 1.1734, 0.    , 0.    ],
       [0.    , 0.    , 0.2186, 0.    ]])

In [8]:
print(np.dot(np.dot(u,sigma),vh))

[[ 1.  2.  3.  4.]
 [ 1.  1.  2.  3.]
 [ 0.  1.  1. -0.]]
