In [19]:
import numpy as np
A1 = np.array([[2,-2, 3],[1, 1, 1],[1, 3, -1]])
print(A)

[[ 2 -2  3]
 [ 1  1  1]
 [ 1  3 -1]]


In [20]:
#Calculate egenpairs
values1 , vectors1 = np.linalg.eig(A)

In [21]:
print(values)

[ 3.  1. -2.]


In [22]:
print(vectors)

[[ 0.57735027  0.57735027 -0.61684937]
 [ 0.57735027 -0.57735027 -0.05607722]
 [ 0.57735027 -0.57735027  0.78508102]]


In [23]:
A2 = np.array([[2, 0, 0],[0, 1, 0],[0, 0, -1]])
print(A2)

[[ 2  0  0]
 [ 0  1  0]
 [ 0  0 -1]]


In [24]:
value2 , vectors2 = np.linalg.eig(A2)

In [25]:
print(value2)

[ 2.  1. -1.]


In [26]:
print(vectors2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
