In [3]:
import numpy as np
p = np.array([[1,2],[3,4],[7,6]])
print(p)

[[1 2]
 [3 4]
 [7 6]]


In [4]:
q = np.array([[1,0],[-1,3],[5,9]])
print(q)

[[ 1  0]
 [-1  3]
 [ 5  9]]


In [6]:
add = np.add(p,q)
print(add)

[[ 2  2]
 [ 2  7]
 [12 15]]


In [7]:
subtract = np.subtract(p,q)
print(subtract)

[[ 0  2]
 [ 4  1]
 [ 2 -3]]


In [8]:
r = np.array([[3,4,6],[1,0,5]])
print(r)

[[3 4 6]
 [1 0 5]]


In [9]:
mul = np.dot(p,r)
print(mul)

[[ 5  4 16]
 [13 12 38]
 [27 28 72]]


In [10]:
det = np.linalg.det(mul)
print(det)

0.0


In [12]:
m = np.array([[1,2],[3,4]])
print(np.linalg.inv(m))

[[-2.   1. ]
 [ 1.5 -0.5]]
