In [1]:
import numpy as np
v = np.array([1,2,3])
w = np.array([2,5,2])

In [2]:
print(v+w)

[3 7 5]


In [3]:
print(v-w)

[-1 -3  1]


In [4]:
#Scalar Mult:
print(3*v)

[3 6 9]


In [5]:
print(np.linalg.norm(v))

3.7416573867739413


In [6]:
s=np.dot(v,w)
print(s)

18
