In [11]:
import numpy as np
np.set_printoptions(precision=4,suppress=True)

In [12]:
a = np.array([[1,2,3,4],[1,1,2,3],[0,1,1,0]])
print(a)

[[1 2 3 4]
 [1 1 2 3]
 [0 1 1 0]]


In [13]:
u, s, vh = np.linalg.svd(a, full_matrices=True)
s

array([6.75094297, 1.17344125, 0.21864263])

In [15]:
sd = np.diag(s)
sd

array([[6.75094297, 0.        , 0.        ],
       [0.        , 1.17344125, 0.        ],
       [0.        , 0.        , 0.21864263]])

In [17]:
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
b[:,:-1] = sd

In [19]:
sigma = b
sigma

array([[6.75094297, 0.        , 0.        , 0.        ],
       [0.        , 1.17344125, 0.        , 0.        ],
       [0.        , 0.        , 0.21864263, 0.        ]])

In [20]:
print(np.dot(np.dot(u,sigma),vh))

[[ 1.00000000e+00  2.00000000e+00  3.00000000e+00  4.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  2.00000000e+00  3.00000000e+00]
 [ 2.83180504e-16  1.00000000e+00  1.00000000e+00 -2.03908195e-16]]
