In [1]:
import numpy as np
from scipy.linalg import svd, sqrtm

In [2]:
# Example matrix
A = np.array([[3, 1],
              [0, 2]])

In [3]:
# Step 1: SVD
U_s, Sigma, Vt = svd(A)

In [8]:
# Step 2: Compute U and P
U = np.dot(U_s, Vt)  # orthogonal/unitary
P = np.dot(np.dot(Vt.T, np.diag(Sigma)), Vt)  # symmetric positive semi-definite


In [9]:
print("Original Matrix A:\n", A)
print("\nOrthogonal/Unitary U:\n", U)
print("\nPositive Semi-Definite P:\n", P)

Original Matrix A:
 [[3 1]
 [0 2]]

Orthogonal/Unitary U:
 [[ 0.98058068  0.19611614]
 [-0.19611614  0.98058068]]

Positive Semi-Definite P:
 [[2.94174203 0.58834841]
 [0.58834841 2.15727749]]


In [10]:
# Verify
print("\nReconstructed A (U*P):\n", np.dot(U, P))


Reconstructed A (U*P):
 [[3.00000000e+00 1.00000000e+00]
 [1.99342109e-16 2.00000000e+00]]
